TypeError: a bytes-like object is required, not 'str'
python socket send and recv do not work with strings. Bytes are needed
instead.

According to the Redis Protocol Spec, the encoding is in "ascii".
https://redis.io/docs/latest/develop/reference/protocol-spec/

Adding the conversion of the data sending to redis and receiving from
redis.